name: build-ui
on:
  push:
    paths:
    - 'source/ui/**'
    - 'include/ui/**'
  workflow_dispatch:
    paths:
      - 'source/ui/**'
      - 'include/ui/**'

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
            sudo apt install -y libsdl2-dev
            cd source/ui
            make
            cd ../../
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-ui-linux-gcc
          path: |
            source/ui/pm-ui
        env:
          CC: gcc
  build-windows-msys2-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, msystem_lower: mingw64, arch: x86_64 }
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2
      - name: build
        run: |
            cd source/ui
            make
            cd ../../
        env:
          CC: gcc
          CXX: g++
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-ui-windows-gcc
          path: |
            source/ui/pm-ui.exe
