name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run tests
        run: cc nobuild.c -o nobuild && ./nobuild test
  build-test-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: run tests
        shell: cmd
        run: |
          cl.exe nobuild.c && nobuild.exe test
