name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cc nobuild.c -o nobuild && ./nobuild test
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cc nobuild.c -onobuild && ./nobuild test
        env:
          CC: clang
  test-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build
        shell: cmd
        run: |
          cl.exe nobuild.c && nobuild.exe test
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cc nobuild.c -onobuild && ./nobuild
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-linux-gcc
          path: |
            pm*
        env:
          CC: gcc
  ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cc nobuild.c -onobuild && ./nobuild
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-linux-clang
          path: |
            pm*
        env:
          CC: clang
  ubuntu-gcc-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq gcc-aarch64-linux-gnu
      - name: build
        run: |
          aarch64-linux-gnu-gcc src/main.c src/io/unix.c src/sync.c src/aes.c src/b64/encode.c src/b64/decode.c src/b64/buffer.c src/io/common.c src/rand.c src/parse.c -Wall -Wextra -pedantic -opm-linux-gcc-unknown-aarch64 -O3
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-linux-clang-12.0.5-aarch64
          path: |
            pm*
  macos-clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cc nobuild.c -onobuild && ./nobuild
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-macos-clang
          path: |
            pm*
        env:
          CC: clang
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build
        shell: cmd
        run: |
          cl nobuild.c && nobuild.exe
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-win-msvc
          path: |
            pm*
