name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: chmod +x *.sh && ./test_console.sh
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          chmod +x *.sh && ./test_console.sh
        env:
          CC: clang
  test-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: test
        shell: cmd
        run: |
          cl /DTEST source/console/test.c source/console/pm_aes.c source/console/pm_b64.c source/console/pm_io.c source/console/pm_parse.c source/console/pm_rand.c source/console/pm_sync.c source/console/pm_xcrypt.c /Iinclude /Fe:test && test.exe
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
            chmod +x *.sh
            ./build_console.sh
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-linux-gcc
          path: |
            pm*
        env:
          CC: gcc
  ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
            chmod +x *.sh
            ./build_console.sh
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-linux-clang
          path: |
            pm*
        env:
          CC: clang
  ubuntu-armv7a-linux-android29-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23
          add-to-path: false
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - run: |
          $NDK/bin/armv7a-linux-androideabi29-clang -Wall -Wextra -pedantic -std=c11 -DNDEBUG -DPM_VERSION=${{ steps.vars.outputs.sha_short }} -Iinclude -I$NDK/sysroot/usr/include source/console/pm_aes.c source/console/pm_b64.c source/console/pm_io.c source/console/pm_parse.c source/console/pm_rand.c source/console/pm_sync.c source/console/pm_xcrypt.c source/console/pm_main.c -opm-linux-clang-unknown-armv7a -O3
        env:
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-linux-clang-unknown-armv7a
          path: |
            pm*
  ubuntu-aarch64-linux-android29-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23
          add-to-path: false
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - run: |
          $NDK/bin/aarch64-linux-android29-clang -Wall -Wextra -pedantic -std=c11 -DNDEBUG -DPM_VERSION=${{ steps.vars.outputs.sha_short }} -Iinclude -I$NDK/sysroot/usr/include source/console/pm_aes.c source/console/pm_b64.c source/console/pm_io.c source/console/pm_parse.c source/console/pm_rand.c source/console/pm_sync.c source/console/pm_xcrypt.c source/console/pm_main.c -opm-linux-clang-unknown-aarch64 -O3
        env:
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-linux-clang-unknown-aarch64
          path: |
            pm*
  macos-clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
            chmod +x *.sh
            ./build_console.sh
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-macos-clang
          path: |
            pm*
        env:
          CC: clang
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: build
        shell: cmd
        run: |
          build_console.bat
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-win-msvc
          path: |
            pm.exe
