name: upload-to-my-repo
on: [workflow_dispatch]

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          chmod +x *.sh
          ./build_console.sh
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-linux-gcc
          path: |
            pm*
        env:
          CC: gcc
  ubuntu-aarch64-linux-android29-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23
          add-to-path: false
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - run: |
          $NDK/bin/aarch64-linux-android29-clang -Wall -Wextra -pedantic -std=c11 -DNDEBUG -DPM_THREAD_COUNT=32 -DPM_VERSION=${{ steps.vars.outputs.sha_short }} -Iinclude -I$NDK/sysroot/usr/include source/console/pm_thread.c source/console/pm_aes.c source/console/pm_b64.c source/console/pm_io.c source/console/pm_parse.c source/console/pm_rand.c source/console/pm_sync.c source/console/pm_xcrypt.c source/console/pm_main.c -opm-linux-clang-unknown-aarch64 -O3
        env:
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-linux-clang-unknown-aarch64
          path: |
            pm*
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: build
        shell: cmd
        run: |
          build_console.bat
      - name: password-manager
        uses: actions/upload-artifact@v2
        with:
          name: pm-win-msvc
          path: |
            pm*
  upload_to_my_repo:
    needs: [ubuntu-gcc, ubuntu-aarch64-linux-android29-clang, windows-msvc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: download pm-linux-gcc
        uses: actions/download-artifact@v2
        with:
          name: pm-linux-gcc
      - name: download pm-win-msvc
        uses: actions/download-artifact@v2
        with:
          name: pm-win-msvc
      - name: download pm-linux-clang-unknown-aarch64
        uses: actions/download-artifact@v2
        with:
          name: pm-linux-clang-unknown-aarch64
      - name: upload artifacts to my repo
        run: |
          git clone git@github.com:Ciremun/pm-data.git data
          cd data
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          cp ../pm* .
          git commit -am "auto_update_binary"
          git push
